version: 2
before:
  hooks:
    - go mod download
    - go generate ./...
    - ./scripts/completions.sh
    - ./scripts/manpages.sh
builds:
- binary: voiceflow
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/xavidop/voiceflow-cli/internal/global.VersionString={{.Version}}
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
  goarm:
    - "7"

archives:
  - name_template: >-
      voiceflow_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE.md
      - completions/*
      - manpages/*

universal_binaries:
- replace: false
  name_template: 'voiceflow_{{.Version}}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

aurs:
  - homepage:  https://voiceflow.xavidop.me
    description: The CLI for your Voiceflow projects
    maintainers:
      - 'Xavier Portilla Edo <xavierportillaedo at gmail dot com>'
    license: Apache-2.0
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/voiceflow-bin.git'
    name: voiceflow
    package: |-
      # bin
      install -Dm755 "./voiceflow" "${pkgdir}/usr/bin/voiceflow"
      # license
      install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/voiceflow/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/voiceflow.bash" "${pkgdir}/usr/share/bash-completion/completions/voiceflow"
      install -Dm644 "./completions/voiceflow.zsh" "${pkgdir}/usr/share/zsh/site-functions/_voiceflow"
      install -Dm644 "./completions/voiceflow.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/voiceflow.fish"

      # man pages
      install -Dm644 "./manpages/voiceflow.1.gz" "${pkgdir}/usr/share/man/man1/voiceflow.1.gz"

nfpms:
  - file_name_template: 'voiceflow_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    package_name: voiceflow
    id: packages
    homepage:  https://voiceflow.xavidop.me
    description: |-
     The CLI to interact with your Voiceflow projects.
    maintainer: Xavier Portilla Edo <xavierportillaedo@gmail.com>
    license: Apache-2.0
    vendor: Xavier Portilla Edo
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/voiceflow.bash
        dst: /usr/share/bash-completion/completions/voiceflow
        file_info:
          mode: 0644
      - src: ./completions/voiceflow.fish
        dst: /usr/share/fish/vendor_completions.d/voiceflow.fish
        file_info:
          mode: 0644
      - src: ./completions/voiceflow.zsh
        dst:  /usr/share/zsh/vendor-completions/_voiceflow
        file_info:
          mode: 0644
      - src: ./LICENSE.md
        dst: /usr/share/doc/voiceflow/copyright
        file_info:
          mode: 0644
      - src: ./manpages/voiceflow.1.gz
        dst: /usr/share/man/man1/voiceflow.1.gz
        file_info:
          mode: 0644
    formats:
    - apk
    - deb
    - rpm
    - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

snapcrafts:
  - name_template: 'voiceflow_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    name: voiceflow
    summary: The CLI to interact with your Voiceflow projects
    description: |
      The CLI to interact with your Voiceflow projects.
    grade: stable
    confinement: strict
    publish: true

dockers:
- image_templates:
  - 'xavidop/voiceflow:{{ .Tag }}-amd64'
  - 'ghcr.io/xavidop/voiceflow:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/xavidop/voiceflow-cli/master/README.md"
  - "--label=io.artifacthub.package.logo-url=https://voiceflow.xavidop.me/images/logo.png"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Xavier Portilla Edo\",\"email\":\"xavierportillaedo@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=Apache-2.0"
  - "--label=org.opencontainers.image.description=The CLI to interact with your Voiceflow projects"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - 'xavidop/voiceflow:{{ .Tag }}-arm64'
  - 'ghcr.io/xavidop/voiceflow:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/xavidop/voiceflow-cli/master/README.md"
  - "--label=io.artifacthub.package.logo-url=https://voiceflow.xavidop.me/images/logo.png"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Xavier Portilla Edo\",\"email\":\"xavierportillaedo@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=Apache-2.0"
  - "--label=org.opencontainers.image.description=The CLI to interact with your Voiceflow projects"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  goarch: arm64

docker_manifests:
- name_template: 'xavidop/voiceflow:{{ .Tag }}'
  image_templates:
  - 'xavidop/voiceflow:{{ .Tag }}-amd64'
  - 'xavidop/voiceflow:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/xavidop/voiceflow:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/xavidop/voiceflow:{{ .Tag }}-amd64'
  - 'ghcr.io/xavidop/voiceflow:{{ .Tag }}-arm64'
- name_template: 'xavidop/voiceflow:latest'
  image_templates:
  - 'xavidop/voiceflow:{{ .Tag }}-amd64'
  - 'xavidop/voiceflow:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/xavidop/voiceflow:latest'
  image_templates:
  - 'ghcr.io/xavidop/voiceflow:{{ .Tag }}-amd64'
  - 'ghcr.io/xavidop/voiceflow:{{ .Tag }}-arm64'

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes

sboms:
  - artifacts: archive
milestones:
  - close: true

scoops:
  - repository:
      owner: xavidop
      name: scoop-bucket
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: voiceflow
    homepage:  https://voiceflow.xavidop.me
    description: The CLI for your Voiceflow projects
    license: Apache-2.0

chocolateys:
  - name: voiceflow
    authors: Xavier Portilla Edo
    title: Voiceflow CLI
    project_url:  https://voiceflow.xavidop.me
    license_url: https://github.com/xavidop/voiceflow-cli/blob/main/LICENSE.md
    project_source_url: https://github.com/xavidop/voiceflow-cli
    docs_url: https://github.com/xavidop/voiceflow-cli/blob/main/README.md
    bug_tracker_url: https://github.com/xavidop/voiceflow-cli/issues
    tags: "voiceflow cli"
    description: The CLI for your Voiceflow projects
    icon_url: https://voiceflow.xavidop.me/images/logo.png
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

brews:
  - repository:
      owner: xavidop
      name: homebrew-tap
    directory: Formula
    name: voiceflow
    homepage: 'https://voiceflow.xavidop.me'
    description: 'The CLI for your Voiceflow projects'
    goarm: "7"
    test: |
      system "#{bin}/voiceflow version"
    commit_author:
      name: xavidop
      email: xavi_tb@hotmail.com
    install: |-
      bin.install "voiceflow"
      bash_completion.install "completions/voiceflow.bash" => "voiceflow"
      zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
      fish_completion.install "completions/voiceflow.fish"
      man1.install "manpages/voiceflow.1.gz"

winget:
  - name: voiceflow
    publisher: xavidop
    license: Apache-2.0
    homepage: https://voiceflow.xavidop.me
    short_description: 'The CLI for your Voiceflow projects'
    repository:
      owner: xavidop
      name: winget-pkgs
      branch: "voiceflow-{{.Version}}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: main


publishers:
  - name: fury.io
    ids:
    - packages
    env:
    - 'FURY_TOKEN={{ .Env.FURY_TOKEN }}'
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

nix:
  - name: voiceflow
    repository:
      owner: xavidop
      name: nur
    homepage: https://voiceflow.xavidop.me
    description: 'The CLI for your Voiceflow projects'
    path: pkgs/voiceflow/default.nix
    license: asl20
    install: |-
      mkdir -p $out/bin
      cp -vr ./voiceflow $out/bin/voiceflow
      installManPage ./manpages/voiceflow.1.gz
      installShellCompletion ./completions/*